#!/usr/bin/env python3
"""
Second-pass targeted translation for remaining Russian strings in Anamnesis frontend.
"""
import os
import re

SRC_DIR = "/data/data/com.termux/files/home/anamnesis/frontend/src"

TRANSLATIONS = [
    # DetailSheet / Modals
    ("Подробное описание", "Detailed description"),
    ("НезависиMay оценка AI", "Independent AI assessment"),
    ("Независимая оценка AI", "Independent AI assessment"),
    ("Подробная информация", "Detailed information"),
    ("Внимание", "Warning"),
    ("Решено", "Resolved"),
    ("Открыто", "Open"),
    ("Recommendations специалиста", "Specialist recommendations"),
    ("Отправлено", "Sent"),
    ("Под вопросом", "Suspected"),
    ("Закрыт", "Closed"),
    ("No диагнозов", "No diagnoses"),
    ("Пусто", "Empty"),
    ("Visitов пока нет", "No visits yet"),
    ("Отдельных документов нет", "No standalone documents"),
    ("Добавьте приём или загрузите документ", "Add a visit or upload a document"),
    ("Скопировано", "Copied"),
    ("Copy промпт", "Copy prompt"),
    ("Loading документа", "Uploading document"),
    ("Убрать файл", "Remove file"),
    ("Привязать к приёму", "Link to visit"),
    ("— Без привязки (отдельный документ) —", "— Standalone document —"),
    ("Новый приём", "New Visit"),
    ("Create приём", "Create visit"),
    ("Не найдено", "Not found"),
    ("Delete приём?", "Delete visit?"),
    ("Привязанные документы останутся. Действие нельзя отменить.", "Linked documents will remain. This action cannot be undone."),
    ("Редактирование", "Edit Visit"),
    ("Save ofменения", "Save changes"),
    ("Ошибок не обнаружено", "No errors found"),
    ("открыть заново", "reopen"),
    ("отметить решённым", "mark as resolved"),
    ("Отметить решённым", "Mark as resolved"),
    ("Name приёма *", "Visit name *"),
    ("ЛОР", "ENT"),
    # More page
    ("Медицинские документы", "Medical Documents"),
    ("Медицинская история", "Medical History"),
    ("Прочее", "Other"),
    ("Интеграции", "Integrations"),
    ("Безопасность", "Security"),
    ("Биометрия", "Biometrics"),
    ("Биометрическая аутентификация", "Biometric Authentication"),
    ("Секретное слово", "Security word"),
    ("Контрольный вопрос", "Security question"),
    ("Сменить PIN", "Change PIN"),
    ("Изменить PIN-код", "Change PIN"),
    ("Резервное копирование", "Backup"),
    ("Резервная копия", "Backup"),
    ("Создать резервную копию", "Create backup"),
    ("Восстановить из резервной копии", "Restore from backup"),
    ("Экспорт данных", "Export data"),
    ("Очистить данные", "Clear data"),
    ("Очистить кэш", "Clear cache"),
    ("Удалить аккаунт", "Delete account"),
    ("О приложении", "About"),
    ("Версия приложения", "App version"),
    ("Политика конфиденциальности", "Privacy policy"),
    ("Условия использования", "Terms of use"),
    ("Конфиденциальность", "Privacy"),
    ("Хранилище", "Storage"),
    ("Занято", "Used"),
    ("Свободно", "Free"),
    ("Всего", "Total"),
    ("Пользователей", "Users"),
    ("Устройств", "Devices"),
    ("Устройство", "Device"),
    ("Этот браузер", "This browser"),
    ("Доверенное устройство", "Trusted device"),
    ("Доверенные устройства", "Trusted devices"),
    ("Отозвать доступ", "Revoke access"),
    ("Подтверждение", "Confirmation"),
    ("Новое устройство", "New device"),
    ("Устройство", "Device"),
    ("Имя устройства (необязательно)", "Device name (optional)"),
    # Plan page
    ("Выполнено", "Done"),
    ("Не выполнено", "Not done"),
    ("В работе", "In progress"),
    ("Ожидание", "Pending"),
    ("Срочно", "Urgent"),
    ("Просроченo", "Overdue"),
    ("Сегодня", "Today"),
    ("Завтра", "Tomorrow"),
    ("На этой неделе", "This week"),
    ("Фильтр по статусу", "Filter by status"),
    ("Фильтр по типу", "Filter by type"),
    ("Все статусы", "All statuses"),
    ("Все типы", "All types"),
    ("Личное", "Personal"),
    ("Медицинское", "Medical"),
    ("Лечение", "Treatment"),
    ("Посещение", "Visit"),
    ("Анализы", "Tests"),
    ("Вакцина", "Vaccine"),
    ("Исследование", "Research"),
    ("Консультация", "Consultation"),
    ("Операция", "Surgery"),
    ("Препарат", "Drug"),
    ("Процедура", "Procedure"),
    # Growth modal
    ("Рост", "Height"),
    ("Вес", "Weight"),
    ("ОГ (окружность головы)", "Head circumference"),
    ("Окружность головы", "Head circumference"),
    ("Возраст", "Age"),
    ("Перцентиль", "Percentile"),
    ("Нормальный", "Normal"),
    ("Выше нормы", "Above normal"),
    ("Ниже нормы", "Below normal"),
    ("Не заполнено", "Not filled"),
    ("Введите рост", "Enter height"),
    ("Введите вес", "Enter weight"),
    ("Введите окружность головы", "Enter head circumference"),
    ("Дата измерения", "Measurement date"),
    # Misc remaining
    ("Отдельный документ", "Standalone document"),
    ("Привязан к приёму", "Linked to visit"),
    ("Документы приёма", "Visit documents"),
    ("Добавить документ к приёму", "Add document to visit"),
    ("Предпросмотр", "Preview"),
    ("Загружен", "Uploaded"),
    ("Обработан", "Processed"),
    ("Обрабатывается", "Processing"),
    ("Ошибка обработки", "Processing error"),
    ("Страница", "Page"),
    ("of", "of"),
    ("стр.", "p."),
    ("Открыть в новой вкладке", "Open in new tab"),
    ("Страница документа", "Document page"),
    ("Нет предпросмотра", "No preview"),
    ("Принят", "Accepted"),
    ("Назначен", "Prescribed"),
    ("Назначение", "Prescription"),
    ("Рекомендован", "Recommended"),
    ("Не принимается", "Not taken"),
    ("Принимается", "Currently taken"),
    ("Курс завершён", "Course completed"),
    ("Постоянно", "Ongoing"),
    ("По необходимости", "As needed"),
    ("Раз в день", "Once a day"),
    ("Два раза в день", "Twice a day"),
    ("Три раза в день", "Three times a day"),
    ("По назначению врача", "As prescribed"),
    ("Перед едой", "Before meals"),
    ("После еды", "After meals"),
    ("Во время еды", "With meals"),
    ("Натощак", "On empty stomach"),
    ("На ночь", "At bedtime"),
    ("Утром", "In the morning"),
    ("Вечером", "In the evening"),
    ("Внутрь", "Orally"),
    ("Подкожно", "Subcutaneously"),
    ("Внутримышечно", "Intramuscularly"),
    ("Внутривенно", "Intravenously"),
    ("Наружно", "Topically"),
    ("Ингаляционно", "By inhalation"),
    ("Капли", "Drops"),
    ("Таблетки", "Tablets"),
    ("Капсулы", "Capsules"),
    ("Сироп", "Syrup"),
    ("Мазь", "Ointment"),
    ("Крем", "Cream"),
    ("Гель", "Gel"),
    ("Раствор", "Solution"),
    ("Суспензия", "Suspension"),
    ("Порошок", "Powder"),
    ("Ампулы", "Ampoules"),
    ("Спрей", "Spray"),
    ("Пластырь", "Patch"),
    ("Суппозитории", "Suppositories"),
    ("Ингалятор", "Inhaler"),
    ("История of изменений", "History of changes"),
    ("История", "History"),
    ("Пользователь", "User"),
    ("Роль", "Role"),
    ("Действие", "Action"),
    ("Объект", "Object"),
    ("Изменения", "Changes"),
    ("До", "Before"),
    ("После", "After"),
    ("Поле", "Field"),
    ("Старое значение", "Old value"),
    ("Новое значение", "New value"),
    ("Нет изменений", "No changes"),
    ("Проверка целостности", "Integrity check"),
    ("Целостность OK", "Integrity OK"),
    ("Нарушение целостности", "Integrity violation"),
    ("Подозрительное изменение", "Suspicious change"),
    ("Контрольная сумма", "Checksum"),
    ("Хеш", "Hash"),
    ("Цифровая подпись", "Digital signature"),
]


def main():
    total_files = 0
    for root, dirs, files in os.walk(SRC_DIR):
        for fname in files:
            if fname.endswith(".tsx") or fname.endswith(".ts"):
                fpath = os.path.join(root, fname)
                with open(fpath, "r", encoding="utf-8") as f:
                    content = f.read()
                original = content
                for ru, en in TRANSLATIONS:
                    content = content.replace(ru, en)
                if content != original:
                    with open(fpath, "w", encoding="utf-8") as f:
                        f.write(content)
                    total_files += 1
    print(f"Done! Updated {total_files} files.")


if __name__ == "__main__":
    main()
