#!/usr/bin/env python3
"""
Full Russian → English translation for Anamnesis frontend.
Targets all .tsx/.ts files under frontend/src.
"""

import os
import re

SRC_DIR = "/data/data/com.termux/files/home/anamnesis/frontend/src"

# Comprehensive dictionary: Russian → English
# Ordered from longest to shortest to avoid partial replacements
TRANSLATIONS = [
    # ---- Multi-word phrases (most specific first) ----
    ("Нет известных аллергий", "No known allergies"),
    ("Нет of активных предупреждений", "No active warnings"),
    ("Нет активных предупреждений", "No active warnings"),
    ("Нет активных диагнозов", "No active diagnoses"),
    ("Нет активных лекарств", "No active medications"),
    ("Нет предстоящих напоминаний", "No upcoming reminders"),
    ("Нет загruженных документов", "No uploaded documents"),
    ("Нет данных для отображения", "No data to display"),
    ("Нет данных", "No data"),
    ("Нет пациентов", "No patients"),
    ("Нет записей", "No records"),
    ("Нет результатов", "No results"),
    ("Нет документов", "No documents"),
    ("Нет приёмов", "No visits"),
    ("Нет ошибок", "No errors"),
    ("Нет напоминаний", "No reminders"),
    ("Нет вакцинаций", "No vaccinations"),
    ("Нет специалистов", "No specialists"),
    ("Нет лекарств", "No medications"),
    ("Нет диагнозов", "No diagnoses"),
    ("Нет роста", "No growth data"),
    ("Нет анализов", "No lab results"),
    ("Подтвердить удаление", "Confirm deletion"),
    ("Вы уверены", "Are you sure"),
    ("Не удалось загрузить", "Failed to load"),
    ("Не удалось сохранить", "Failed to save"),
    ("Не удалось удалить", "Failed to delete"),
    ("Не удалось", "Failed to"),
    ("Пожалуйста подождите", "Please wait"),
    ("Загрузка данных", "Loading data"),
    ("Сохранение данных", "Saving data"),
    ("Загрузка файла", "Uploading file"),
    ("Загрузка документа", "Uploading document"),
    ("Удаление записи", "Deleting record"),
    ("Произошла ошибка", "An error occurred"),
    ("Попробуйте снова", "Try again"),
    ("Повторить попытку", "Retry"),
    ("Нет токена в ответе", "No token in response"),
    ("No токена в ответе", "No token in response"),
    ("No токена", "No token"),
    ("Нет подключения к серверу", "No connection to server"),
    ("Нет соединения", "No connection"),
    ("Добавить нового пациента", "Add new patient"),
    ("Добавить пациента", "Add patient"),
    ("Выберите пациента", "Select patient"),
    ("Переключить пациента", "Switch patient"),
    ("Редактировать пациента", "Edit patient"),
    ("Информация о пациенте", "Patient information"),
    ("Добавить диагноз", "Add diagnosis"),
    ("Редактировать диагноз", "Edit diagnosis"),
    ("Удалить диагноз", "Delete diagnosis"),
    ("Добавить лекарство", "Add medication"),
    ("Редактировать лекарство", "Edit medication"),
    ("Удалить лекарство", "Delete medication"),
    ("Добавить напоминание", "Add reminder"),
    ("Редактировать напоминание", "Edit reminder"),
    ("Удалить напоминание", "Delete reminder"),
    ("Добавить специалиста", "Add specialist"),
    ("Редактировать специалиста", "Edit specialist"),
    ("Удалить специалиста", "Delete specialist"),
    ("Добавить запись", "Add record"),
    ("Добавить приём", "Add visit"),
    ("Редактировать приём", "Edit visit"),
    ("Удалить приём", "Delete visit"),
    ("Добавить документ", "Add document"),
    ("Удалить документ", "Delete document"),
    ("Добавить вакцинацию", "Add vaccination"),
    ("Редактировать вакцинацию", "Edit vaccination"),
    ("Удалить вакцинацию", "Delete vaccination"),
    ("Добавить анализ", "Add lab result"),
    ("Редактировать анализ", "Edit lab result"),
    ("Удалить анализ", "Delete lab result"),
    ("Добавить ошибку", "Add error"),
    ("Редактировать ошибку", "Edit error"),
    ("Удалить ошибку", "Delete error"),
    ("Дата рождения", "Date of birth"),
    ("Дата приёма", "Visit date"),
    ("Дата документа", "Document date"),
    ("Дата создания", "Date created"),
    ("Дата обновления", "Date updated"),
    ("Дата и время", "Date and time"),
    ("Дата начала", "Start date"),
    ("Дата окончания", "End date"),
    ("Имя пациента", "Patient name"),
    ("Полное имя", "Full name"),
    ("Имя врача", "Doctor name"),
    ("Имя специалиста", "Specialist name"),
    ("ФИО врача (если нет в списке)", "Doctor name (if not in list)"),
    ("Или вручную: имя врача", "Or manually: doctor name"),
    ("Или вручную", "Or manually"),
    ("Специализация врача", "Doctor specialization"),
    ("Контактные данные", "Contact details"),
    ("Место рождения", "Place of birth"),
    ("Город проживания", "City of residence"),
    ("Место жительства", "Place of residence"),
    ("Дата рождения (ГГГГ-ММ-ДД)", "Date of birth (YYYY-MM-DD)"),
    ("Вес при рождении (г)", "Birth weight (g)"),
    ("Текущий рост (см)", "Current height (cm)"),
    ("Текущий вес (кг)", "Current weight (kg)"),
    ("Группа крови", "Blood type"),
    ("Аллергии", "Allergies"),
    ("Код МКБ", "ICD code"),
    ("Дата постановки", "Diagnosis date"),
    ("Дата выявления", "Detection date"),
    ("Статус диагноза", "Diagnosis status"),
    ("Название лекарства", "Medication name"),
    ("Дозировка", "Dosage"),
    ("Частота приёма", "Frequency"),
    ("Дата начала приёма", "Start date"),
    ("Дата окончания приёма", "End date"),
    ("Причина назначения", "Reason for prescription"),
    ("Название вакцины", "Vaccine name"),
    ("Серия вакцины", "Vaccine batch"),
    ("Дата вакцинации", "Vaccination date"),
    ("Следующая доза", "Next dose"),
    ("Место проведения", "Location"),
    ("Название анализа", "Lab test name"),
    ("Результат анализа", "Lab result"),
    ("Единица измерения", "Unit of measure"),
    ("Референсные значения", "Reference values"),
    ("Норма", "Normal"),
    ("Тип приёма", "Visit type"),
    ("Название приёма", "Visit title"),
    ("Заключение врача", "Doctor's conclusion"),
    ("Дополнительные заметки", "Additional notes"),
    ("Название документа", "Document title"),
    ("Тип документа", "Document type"),
    ("Категория документа", "Document category"),
    ("Приоритет ошибки", "Error priority"),
    ("Статус ошибки", "Error status"),
    ("Название ошибки", "Error title"),
    ("Описание ошибки", "Error description"),
    ("Дата ошибки", "Error date"),
    ("Дата напоминания", "Reminder date"),
    ("Текст напоминания", "Reminder text"),
    ("Название напоминания", "Reminder title"),
    ("Тип напоминания", "Reminder type"),
    ("Повтор напоминания", "Reminder repeat"),
    ("Сохранить изменения", "Save changes"),
    ("Сохранить и закрыть", "Save and close"),
    ("Отменить изменения", "Cancel changes"),
    ("Подтвердить действие", "Confirm action"),
    ("Закрыть модальное окно", "Close window"),
    ("Открыть документ", "Open document"),
    ("Скачать документ", "Download document"),
    ("Просмотр документа", "View document"),
    ("Загрузить документ", "Upload document"),
    ("Загрузить файл", "Upload file"),
    ("Выберите файл", "Select file"),
    ("Перетащите файл", "Drag file here"),
    ("Поддерживаемые форматы", "Supported formats"),
    ("Максимальный размер", "Maximum size"),
    ("Файл загружен", "File uploaded"),
    ("Файл удалён", "File deleted"),
    ("Ошибка загрузки", "Upload error"),
    ("Успешно сохранено", "Successfully saved"),
    ("Успешно удалено", "Successfully deleted"),
    ("Данные обновлены", "Data updated"),
    ("Изменения сохранены", "Changes saved"),
    ("Запись удалена", "Record deleted"),
    ("Операция выполнена", "Operation completed"),
    ("Обновление...", "Updating..."),
    ("Загрузка...", "Loading..."),
    ("Сохранение...", "Saving..."),
    ("Удаление...", "Deleting..."),
    ("Пожалуйста, подождите", "Please wait"),
    ("Обработка запроса", "Processing request"),
    ("Запрос выполнен", "Request completed"),
    ("Запрос отправлен", "Request sent"),
    ("Ответ получен", "Response received"),
    ("AI анализ", "AI analysis"),
    ("AI запрос", "AI request"),
    ("AI ответ", "AI response"),
    ("AI сводка", "AI summary"),
    ("AI чат", "AI Chat"),
    ("Отправить запрос к AI", "Send AI request"),
    ("Генерация AI ответа", "Generating AI response"),
    ("Запрос к AI", "AI Request"),
    ("История изменений", "Change history"),
    ("История приёмов", "Visit history"),
    ("История лечения", "Treatment history"),
    ("Карта здоровья", "Health Graph"),
    ("График роста", "Growth chart"),
    ("График веса", "Weight chart"),
    ("Динамика", "Dynamics"),
    ("Показатели", "Indicators"),
    ("Параметры", "Parameters"),
    ("Период", "Period"),
    ("Все записи", "All records"),
    ("Последние записи", "Recent records"),
    ("Активные диагнозы", "Active diagnoses"),
    ("Активные лекарства", "Active medications"),
    ("Открытые ошибки", "Open errors"),
    ("Предстоящие напоминания", "Upcoming reminders"),
    ("Последние приёмы", "Recent visits"),
    ("Все приёмы", "All visits"),
    ("Все документы", "All documents"),
    ("Все диагнозы", "All diagnoses"),
    ("Все лекарства", "All medications"),
    ("Все вакцинации", "All vaccinations"),
    ("Все анализы", "All lab results"),
    ("Все ошибки", "All errors"),
    ("Все напоминания", "All reminders"),
    ("Все специалисты", "All specialists"),
    ("Поиск пациента", "Search patient"),
    ("Поиск по пациентам", "Search patients"),
    ("Поиск диагноза", "Search diagnosis"),
    ("Поиск лекарства", "Search medication"),
    ("Поиск документа", "Search document"),
    ("Поиск записи", "Search record"),
    ("Результаты поиска", "Search results"),
    ("Введите запрос", "Enter query"),
    ("Введите текст", "Enter text"),
    ("Введите имя", "Enter name"),
    ("Введите название", "Enter title"),
    ("Введите описание", "Enter description"),
    ("Поиск...", "Search..."),
    ("Без имени", "(no name)"),
    ("без имени", "(no name)"),
    ("Без названия", "Untitled"),
    ("Без специализации", "No specialization"),
    ("Без категории", "No category"),
    ("Без описания", "No description"),
    ("Нет данных для графика", "No chart data"),
    ("Демонстрационное напоминание. Замените своими после подключения AI.", "Demo reminder. Replace with your own after connecting AI."),
    ("Демо-пациент", "Demo patient"),
    ("Демо данные", "Demo data"),
    ("Демонстрационные данные", "Demo data"),
    ("Расшифровка приёма", "Visit Transcription"),
    ("Расшифровка", "Transcription"),
    ("Промпт для NotebookLM", "NotebookLM Prompt"),
    ("Расшифровка (of NotebookLM)", "Transcription (from NotebookLM)"),
    ("Description / заключение", "Description / Conclusion"),
    ("Аналof AI", "AI Analysis"),
    ("Вставьте расшифровку аудиоrecords of NotebookLM или другого сервиса транскрипции.", "Paste transcription from NotebookLM or another transcription service."),
    ("Вставьте расшифровку аудиоrecords of NotebookLM", "Paste transcription from NotebookLM"),
    ("Например: Приём невролога", "E.g.: Neurology appointment"),
    ("Краткое описание вofита или заключение врача", "Brief description or doctor's conclusion"),
    ("— Выберите of списка —", "— Select from list —"),
    ("— Выберите —", "— Select —"),
    ("Выберите of списка", "Select from list"),
    ("Добавить комментарий", "Add comment"),
    ("Редактировать комментарий", "Edit comment"),
    ("Удалить комментарий", "Delete comment"),
    ("Комментарии", "Comments"),
    ("Комментарий", "Comment"),
    ("Нет комментариев", "No comments"),
    ("Введите комментарий...", "Enter comment..."),
    ("Отправить", "Submit"),
    ("Отмена", "Cancel"),
    ("Закрыть", "Close"),
    ("Сохранить", "Save"),
    ("Удалить", "Delete"),
    ("Редактировать", "Edit"),
    ("Добавить", "Add"),
    ("Создать", "Create"),
    ("Применить", "Apply"),
    ("Сбросить", "Reset"),
    ("Обновить", "Refresh"),
    ("Повторить", "Retry"),
    ("Подтвердить", "Confirm"),
    ("Назад", "Back"),
    ("Вперёд", "Next"),
    ("Далее", "Next"),
    ("Готово", "Done"),
    ("Загрузить", "Upload"),
    ("Скачать", "Download"),
    ("Открыть", "Open"),
    ("Просмотр", "View"),
    ("Подробнее", "Details"),
    ("Развернуть", "Expand"),
    ("Свернуть", "Collapse"),
    ("Скопировать", "Copy"),
    ("Поделиться", "Share"),
    ("Экспорт", "Export"),
    ("Импорт", "Import"),
    ("Печать", "Print"),
    ("Фильтр", "Filter"),
    ("Сортировка", "Sort"),
    ("Группировка", "Group"),
    ("Настройки", "Settings"),
    ("Профиль", "Profile"),
    ("Выход", "Logout"),
    ("Войти", "Login"),
    ("Пароль", "Password"),
    ("Логин", "Login"),
    ("Регистрация", "Register"),
    ("Забыли пароль", "Forgot password"),
    # ---- Visit / Document types ----
    ("Приём", "Visit"),
    ("Обследование", "Examination"),
    ("Госпитализация", "Hospitalization"),
    ("Событие", "Event"),
    ("Снимки", "Images"),
    ("Рецепт", "Prescription"),
    ("Заключение", "Report"),
    ("Другое", "Other"),
    # ---- Months ----
    ("янв", "Jan"),
    ("фев", "Feb"),
    ("мар", "Mar"),
    ("апр", "Apr"),
    ("мая", "May"),
    ("июн", "Jun"),
    ("июл", "Jul"),
    ("авг", "Aug"),
    ("сен", "Sep"),
    ("окт", "Oct"),
    ("ноя", "Nov"),
    ("дек", "Dec"),
    # ---- Medical specialties ----
    ("Невролог", "Neurologist"),
    ("Педиатр", "Pediatrician"),
    ("Логопед", "Speech Therapist"),
    ("Психолог", "Psychologist"),
    ("Психиатр", "Psychiatrist"),
    ("Ортопед", "Orthopedist"),
    ("Офтальмолог", "Ophthalmologist"),
    ("Стоматолог", "Dentist"),
    ("Хирург", "Surgeon"),
    ("Аллерголог", "Allergist"),
    ("Дерматолог", "Dermatologist"),
    ("Гастроэнтеролог", "Gastroenterologist"),
    ("Кардиолог", "Cardiologist"),
    ("Эндокринолог", "Endocrinologist"),
    ("Уролог", "Urologist"),
    ("Нефролог", "Nephrologist"),
    ("Остеопат", "Osteopath"),
    ("Реабилитолог", "Rehabilitation Specialist"),
    ("Другой специалист", "Other Specialist"),
    # ---- Status labels ----
    ("активный", "active"),
    ("активная", "active"),
    ("активное", "active"),
    ("Активный", "Active"),
    ("Активная", "Active"),
    ("Активное", "Active"),
    ("завершён", "completed"),
    ("завершена", "completed"),
    ("Завершён", "Completed"),
    ("Завершена", "Completed"),
    ("отменён", "cancelled"),
    ("отменена", "cancelled"),
    ("Отменён", "Cancelled"),
    ("Отменена", "Cancelled"),
    ("в процессе", "in progress"),
    ("В процессе", "In progress"),
    ("запланирован", "planned"),
    ("Запланирован", "Planned"),
    ("открыта", "open"),
    ("Открыта", "Open"),
    ("закрыта", "closed"),
    ("Закрыта", "Closed"),
    ("критическая", "critical"),
    ("Критическая", "Critical"),
    ("высокая", "high"),
    ("Высокая", "High"),
    ("средняя", "medium"),
    ("Средняя", "Medium"),
    ("низкая", "low"),
    ("Низкая", "Low"),
    # ---- Gender ----
    ("Мужской", "Male"),
    ("Женский", "Female"),
    ("мужской", "male"),
    ("женский", "female"),
    ("М", "M"),
    # ---- Common UI words ----
    ("Документ", "Document"),
    ("Запись", "Record"),
    ("Врач", "Doctor"),
    ("Специалист", "Specialist"),
    ("Пациент", "Patient"),
    ("Родитель", "Parent"),
    ("Диагноз", "Diagnosis"),
    ("Лекарство", "Medication"),
    ("Напоминание", "Reminder"),
    ("Вакцинация", "Vaccination"),
    ("Анализ", "Lab Result"),
    ("Ошибка", "Error"),
    ("Дата", "Date"),
    ("Время", "Time"),
    ("Имя", "Name"),
    ("Фамилия", "Last name"),
    ("Телефон", "Phone"),
    ("Email", "Email"),
    ("Адрес", "Address"),
    ("Город", "City"),
    ("Страна", "Country"),
    ("Примечание", "Note"),
    ("Заметка", "Note"),
    ("Описание", "Description"),
    ("Категория", "Category"),
    ("Тип", "Type"),
    ("Статус", "Status"),
    ("Приоритет", "Priority"),
    ("Теги", "Tags"),
    ("Тег", "Tag"),
    ("Код", "Code"),
    ("Номер", "Number"),
    ("Значение", "Value"),
    ("Единица", "Unit"),
    ("Файл", "File"),
    ("Изображение", "Image"),
    ("Фото", "Photo"),
    ("Ссылка", "Link"),
    ("Источник", "Source"),
    ("Результат", "Result"),
    ("Ответ", "Answer"),
    ("Вопрос", "Question"),
    ("Комментарий", "Comment"),
    ("Заголовок", "Title"),
    ("Название", "Name"),
    ("Текст", "Text"),
    ("Содержание", "Content"),
    ("Раздел", "Section"),
    ("Страница", "Page"),
    ("Меню", "Menu"),
    ("Кнопка", "Button"),
    ("Форма", "Form"),
    ("Поле", "Field"),
    ("Список", "List"),
    ("Таблица", "Table"),
    ("График", "Chart"),
    ("Карта", "Map"),
    ("Карточка", "Card"),
    ("Блок", "Block"),
    ("Панель", "Panel"),
    ("Вкладка", "Tab"),
    ("Окно", "Window"),
    ("Модальное окно", "Modal"),
    ("Уведомление", "Notification"),
    ("Предупреждение", "Warning"),
    ("Ошибки", "Errors"),
    ("Информация", "Information"),
    ("Подсказка", "Hint"),
    ("Справка", "Help"),
    ("Инструкция", "Instructions"),
    ("Документация", "Documentation"),
    ("Версия", "Version"),
    ("Обновление", "Update"),
    ("Syncing", "Syncing"),
    ("Синхронизация", "Sync"),
]


def translate_file(path: str) -> int:
    """Return number of replacements made."""
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
    original = content
    for ru, en in TRANSLATIONS:
        # Replace inside string literals (between quotes) and JSX text
        # Simple replace is safe here since strings are specific enough
        content = content.replace(ru, en)
    if content != original:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return content.count("") - original.count("")  # placeholder
    return 0


def main():
    total_files = 0
    for root, dirs, files in os.walk(SRC_DIR):
        for fname in files:
            if fname.endswith(".tsx") or fname.endswith(".ts"):
                fpath = os.path.join(root, fname)
                with open(fpath, "r", encoding="utf-8") as f:
                    content = f.read()
                original = content
                for ru, en in TRANSLATIONS:
                    content = content.replace(ru, en)
                if content != original:
                    with open(fpath, "w", encoding="utf-8") as f:
                        f.write(content)
                    total_files += 1
    print(f"Done! Updated {total_files} files.")


if __name__ == "__main__":
    main()
